"""add parsed job fields

Revision ID: 07feb8613a89
Revises: 19cd52d2a1fc
Create Date: 2026-07-14 15:06:31.245192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07feb8613a89'
down_revision: Union[str, Sequence[str], None] = '19cd52d2a1fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_jobs', sa.Column('location', sa.Text(), nullable=True))
    op.add_column('parsed_jobs', sa.Column('employment_type', sa.Text(), nullable=True))
    op.add_column('parsed_jobs', sa.Column('job_summary', sa.Text(), nullable=True))
    op.add_column('parsed_jobs', sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('parsed_jobs', sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('parsed_jobs', sa.Column('certifications', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('parsed_jobs', sa.Column('soft_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('parsed_jobs', sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('parsed_jobs', sa.Column('parsed_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsed_jobs', 'parsed_json')
    op.drop_column('parsed_jobs', 'keywords')
    op.drop_column('parsed_jobs', 'soft_skills')
    op.drop_column('parsed_jobs', 'certifications')
    op.drop_column('parsed_jobs', 'technologies')
    op.drop_column('parsed_jobs', 'preferred_skills')
    op.drop_column('parsed_jobs', 'job_summary')
    op.drop_column('parsed_jobs', 'employment_type')
    op.drop_column('parsed_jobs', 'location')
    # ### end Alembic commands ###
