"""add ai fields to parsed_resume

Revision ID: 19cd52d2a1fc
Revises: 51535006d58a
Create Date: 2026-07-14 14:02:22.549017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19cd52d2a1fc'
down_revision: Union[str, Sequence[str], None] = '51535006d58a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_resumes', sa.Column('summary', sa.Text(), nullable=True))
    op.add_column('parsed_resumes', sa.Column('technologies', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('parsed_resumes', sa.Column('languages', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('parsed_resumes', sa.Column('achievements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('parsed_resumes', sa.Column('years_experience', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsed_resumes', 'years_experience')
    op.drop_column('parsed_resumes', 'achievements')
    op.drop_column('parsed_resumes', 'languages')
    op.drop_column('parsed_resumes', 'technologies')
    op.drop_column('parsed_resumes', 'summary')
    # ### end Alembic commands ###
