"""add_ats_fields_to_parsed_resume

Revision ID: 2dc77ac6d321
Revises: 951beb6aba93
Create Date: 2026-07-16 01:09:38.394254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2dc77ac6d321'
down_revision: Union[str, Sequence[str], None] = '951beb6aba93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parsed_resumes', sa.Column('ats_score', sa.Integer(), nullable=True))
    op.add_column('parsed_resumes', sa.Column('ats_strengths', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('parsed_resumes', sa.Column('ats_weaknesses', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('parsed_resumes', sa.Column('ats_suggestions', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('parsed_resumes', 'ats_suggestions')
    op.drop_column('parsed_resumes', 'ats_weaknesses')
    op.drop_column('parsed_resumes', 'ats_strengths')
    op.drop_column('parsed_resumes', 'ats_score')
    # ### end Alembic commands ###
