"""add tailored resumes table

Revision ID: 554aa19382c7
Revises: 07feb8613a89
Create Date: 2026-07-14 16:24:45.672545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '554aa19382c7'
down_revision: Union[str, Sequence[str], None] = '07feb8613a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tailored_resumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('resume_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('tailored_summary', sa.Text(), nullable=True),
    sa.Column('tailored_experience', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tailored_projects', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ats_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('overall_match', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job_descriptions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tailored_resumes_id'), 'tailored_resumes', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tailored_resumes_id'), table_name='tailored_resumes')
    op.drop_table('tailored_resumes')
    # ### end Alembic commands ###
