"""add metadata fields to jobs

Revision ID: ddf9c89f1909
Revises: 357e07c502f9
Create Date: 2026-07-13 20:54:12.399984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddf9c89f1909'
down_revision: Union[str, Sequence[str], None] = '357e07c502f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job_descriptions', sa.Column('title', sa.String(length=255), nullable=True))
    op.add_column('job_descriptions', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('job_descriptions', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('job_descriptions', sa.Column('source', sa.String(length=100), nullable=True))
    op.add_column('job_descriptions', sa.Column('job_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job_descriptions', 'job_url')
    op.drop_column('job_descriptions', 'source')
    op.drop_column('job_descriptions', 'location')
    op.drop_column('job_descriptions', 'company')
    op.drop_column('job_descriptions', 'title')
    # ### end Alembic commands ###
